[theme]
# Primary accent color for interactive elements.
primaryColor = "#ffe400"

# Background color for the main content area.
backgroundColor = "#ff1c3a"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#a2a2a4"

# Color used for almost all text.
textColor = "#ffffff"